name: Auto Merge Pull Request Workflow
'on':
  workflow_call: null
jobs:
  bot_merge:
    name: Merge
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    strategy:
      matrix:
        author:
          - 'dependabot[bot]'
          - uefibot
    steps:
      - name: Auto Merge
        id: auto_merge
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: '${{ secrets.PROJECT_MU_BOT_TOKEN }}'
          MERGE_ERROR_FAIL: 'false'
          MERGE_FILTER_AUTHOR: '${{ matrix.author }}'
          MERGE_FORKS: 'false'
          MERGE_LABELS: >-
            !state:duplicate,!state:invalid,!state:needs-maintainer-feedback,!state:needs-submitter-info,!state:under-discussion,!state:wont-fix,!type:notes,!type:question
          MERGE_METHOD: squash
          MERGE_REMOVE_LABELS: = ""
          MERGE_RETRIES: '180'
          MERGE_RETRY_SLEEP: '60000'
          UPDATE_LABELS: ''
          UPDATE_METHOD: rebase
          UPDATE_RETRIES: '120'
          UPDATE_RETRY_SLEEP: '60000'
