name: Enable automerge on dependabot PRs
'on':
  pull_request_target: null
jobs:
  automerge:
    name: Enable automerge on dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1
        with:
          github-token: $'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'
          allowed-author: 'dependabot[bot]'
          merge-method: MERGE
